version: 1.1.0
avatar: /img/avatar.jpg
favicon: /img/favicon.png

blog_path: /

link:
  theme: color
  items:
    rss: /atom.xml
    github: https://github.com/pooza
    email: support@precure.ml

author:
  on: false

category:
  num: true
  sub: true
  sort:
    - 读书
    - 工具
    - 大前端
    - 后端
    - 数据库
    - 运维
  width:
    lg: 240
    md: 200
    sm: 180

shortcutKey: true

menu:
  about:
    on: true
    url: /about
  friend:
    on: false
  menus:
    相册:
      on: false
      url: /photo
      type: 1  # 跳转类型 1：站内异步跳转
    叶落阁:
      on: false
      url: http://yelog.org/
      type: 2  # 跳转类型 2：当前页面跳转
    github:
      on: false
      url: https://github.com/yelog
      type: 3  # 跳转类型 3：打开新的tab页


bottom_text: ©2019-2020 b-shock. co., ltd.

reward: true

searchAll: true

toc:
  max_depth: 3

article_list:
  title: '#383636'
  datetime: '#5e5e5f'
  hover:
    background: '#e2e0e0'
    color:

article_bg_img:
  on: false

list: normal

blockquote: github

table: green_title

index_bg_img:
other_bg_img:

img_resize: default

code:
  theme: dark-red

highlight:
  on: true # true开启代码高亮
  lineNum: false # true显示行号
  theme: atom-light

mathjax:
  on: true #是否启用
  per_page: false # 若只渲染单个页面，此选项设为false，页面内加入 mathjax: true

mermaid:
  on: false
  cdn: //cdn.jsdelivr.net/npm/mermaid@8.4.2/dist/mermaid.min.js
  options:
    theme: 'default'
    startOnLoad: true
    flowchart:
      useMaxWidth: false
      htmlLabels: true

comment:
  on: false

gitalk:
  githubID: yelog
  repo: yelog.github.io
  ClientID:
  ClientSecret:
  adminUser: yelog
  distractionFreeMode: true
  language: ja
  perPage: 10

gitment:
  owner: yelog
  repo: yelog.github.io
  client_id:
  client_secret:

livere:
  data_uid:

utteranc:
  repo: xxx/xxx.github.io # 承载评论的仓库，填上自己新建的仓库
  issue_term: pathname    # Issue 与 博客文章 之间映射关系
  label: utteranc         # 创建的 Issue 添加的标签
  theme: github-light     # 主题，可选主题请查看官方文档 https://utteranc.es/#heading-theme

CDN:
  jquery: //cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  jquery_cookie: //cdn.jsdelivr.net/npm/jquery.cookie@1.4.1/jquery.cookie.min.js
  highlight: //cdn.jsdelivr.net/npm/highlightjs@9.16.2/highlight.pack.min.js
  pjax: //cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min.js
  animate: //cdn.jsdelivr.net/npm/animate.css@4.1.0/animate.min.css
  nprogres_js: //cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js
  mathjax: //cdn.jsdelivr.net/npm/mathjax@2.7.8/unpacked/MathJax.js?config=TeX-MML-AM_CHTML
  photoswipe_js: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.js
  photoswipe_ui_js: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js
  photoswipe_css: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.css
  photoswipe_skin_css: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.min.css
